# Generated by Django 5.1.1 on 2024-09-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=True, verbose_name='is_premium'),
        ),
    ]
