# Generated by Django 5.1.1 on 2024-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='プレミアム会員かどうかを示します。', verbose_name='is_premium'),
        ),
    ]
